### ISSUE TITLE
Plans to make Scour compatible with Python 3.x?

### ISSUE THREAD

**Issue by jkphl** [oberstet/scour#4]
Sorry for this potentially silly question, but are there any plans to make Scour compatible with Python 3.x? Is that possible (or reasonable) at all? I must admit that I have no clue of Python, so I don't really understand the implications of my question. The only thing I know is that I had to take special measurements on our servers to be able to use Scour, as Python 2.x is not necessarily the default Python interpreter on our servers. Thanks for enlightening me! ;)

Cheers,
Joschi

**Comment by Jenselme** [comment]
Any progress on that? Can I help?

**Comment by oberstet** [comment]
If anyone is doing the work, sure;) Unfort., I don't have time .. and it's only a "tool", so the impact of only being able to run under Py 2 is minor.
