### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by SimonSteinberger** [oberstet/scour#9]
Using relative import paths inside scour.py doesn't work when calling the script from outside the package directory:

ValueError: Attempted relative import in non-package

    from .svg_regex import svg_parser

Should be

    from svg_regex import svg_parser

The same for two other relative imports inside this file.

**Comment by oberstet** [comment]
Youd shouldn't call the script, but use the installed `scour` binary (https://github.com/oberstet/scour/blob/master/setup.py#L49)
